import Head from 'next/head'
import React from 'react';
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Nav_Bar from './nav-bar';
import Menu from './Menu'
import Footer from './Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home({ mainHeaderText}) {
  return (
    <>
      <Head>
        <title>Loft Maker London Ltd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>
      <main>
      <Nav_Bar/>
      <Menu/>
      


      <section className='Gallery_FlexBox'>
          <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                            
                            width: 'auto ',
                            height: '45vh',
                          }} />
          <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                            
                            width: 'auto ',
                            height: '45vh',
                          }} />

            <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                                    
                                    width: 'auto ',
                                    height: '45vh',
                                  }} />

            <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                                                
                                                width: 'auto ',
                                                height: '45vh',
                                              }} />
            <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                                                
                                                width: 'auto ',
                                                height: '45vh',
                                              }} />

<Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                            
                            width: 'auto ',
                            height: '45vh',
                          }} />
          <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                            
                            width: 'auto ',
                            height: '45vh',
                          }} />

            <Image className='Gallery_FlexBox_image'  loading='lazy' src="/En2AL/Tap981.jpg" width={596} height={795} blurDataURL="data:..." placeholder="blur" alt="Tap" style={{
                                    
                                    width: 'auto ',
                                    height: '45vh',
                                  }} />

            

      </section>
      <Footer/>
  
  

      
      </main>
    </>
  )
}


